services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=mydb
    volumes:
      - db_dev_data:/var/lib/postgresql/data

volumes:
  db_dev_data:
